//go:build gui && windows

package main

import (
	"bytes"
	"errors"
	"fmt"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type guiRunOutput struct {
	mu       sync.Mutex
	buffer   bytes.Buffer
	progress func(progressState)
}

func (output *guiRunOutput) Write(data []byte) (int, error) {
	output.mu.Lock()
	defer output.mu.Unlock()
	return output.buffer.Write(data)
}

func (output *guiRunOutput) String() string {
	output.mu.Lock()
	defer output.mu.Unlock()
	return output.buffer.String()
}

func (output *guiRunOutput) reportProgress(state progressState) {
	if output.progress != nil {
		output.progress(state)
	}
}

type guiView struct {
	window            fyne.Window
	root              *widget.Entry
	mode              *widget.RadioGroup
	extensions        *widget.Entry
	exclusions        *widget.Entry
	contentExclusions *widget.Entry
	contentMaxMiB     *widget.SelectEntry
	workers           *widget.SelectEntry
	previewCount      *widget.SelectEntry
	keepPreview       *widget.SelectEntry
	emptyDirPreview   *widget.SelectEntry
	logPath           *widget.Entry
	noExtension       *widget.Check
	invert            *widget.Check
	emptyDirs         *widget.Check
	ignoreScanErrors  *widget.Check
	browse            *widget.Button
	previewButton     *widget.Button
	executeButton     *widget.Button
	status            *widget.Label
	progress          *widget.ProgressBar
	progressInfinite  *widget.ProgressBarInfinite
	output            *widget.TextGrid
	controls          []fyne.Disableable
	lastPreview       string
	running           bool
}

func main() {
	application := app.NewWithID("io.github.youxiefengjing.filetype-cleaner")
	window := application.NewWindow("文件类型清理器")
	window.SetIcon(theme.FolderOpenIcon())
	window.Resize(fyne.NewSize(1120, 740))

	view := newGUIView(window)
	window.SetContent(view.content())
	window.ShowAndRun()
}

func newGUIView(window fyne.Window) *guiView {
	view := &guiView{window: window}
	view.root = widget.NewEntry()
	view.root.SetPlaceHolder("选择要扫描的根目录")

	view.mode = widget.NewRadioGroup([]string{guiModeDelete, guiModeFlatten}, nil)
	view.mode.Horizontal = true
	view.mode.Required = true
	view.mode.SetSelected(guiModeDelete)

	view.extensions = widget.NewEntry()
	view.extensions.SetPlaceHolder("例如 .c,.h；展平模式可留空")
	view.exclusions = widget.NewEntry()
	view.exclusions.SetPlaceHolder("例如 vendor,temp")
	view.contentExclusions = widget.NewEntry()
	view.contentExclusions.SetPlaceHolder("例如 generated by,do not delete")

	view.contentMaxMiB = widget.NewSelectEntry([]string{"0", "16", "64", "256"})
	view.contentMaxMiB.SetText("16")
	view.workers = widget.NewSelectEntry([]string{"1", "2", "4", "8", "16"})
	defaultWorkers := runtime.NumCPU()
	if defaultWorkers > 4 {
		defaultWorkers = 4
	}
	if defaultWorkers < 1 {
		defaultWorkers = 1
	}
	view.workers.SetText(strconv.Itoa(defaultWorkers))
	view.previewCount = widget.NewSelectEntry([]string{"0", "20", "50", "100"})
	view.previewCount.SetText("20")
	view.keepPreview = widget.NewSelectEntry([]string{"0", "20", "50", "100"})
	view.keepPreview.SetText("20")
	view.emptyDirPreview = widget.NewSelectEntry([]string{"0", "20", "50", "100"})
	view.emptyDirPreview.SetText("20")

	view.logPath = widget.NewEntry()
	view.logPath.SetPlaceHolder("可选，例如 cleanup.log")
	view.noExtension = widget.NewCheck("无扩展名", nil)
	view.invert = widget.NewCheck("反向模式", nil)
	view.emptyDirs = widget.NewCheck("处理空文件夹", nil)
	view.ignoreScanErrors = widget.NewCheck("扫描有错误时仍允许执行", nil)

	view.status = widget.NewLabel("就绪")
	view.progress = widget.NewProgressBar()
	view.progress.Hide()
	view.progressInfinite = widget.NewProgressBarInfinite()
	view.progressInfinite.Hide()
	view.output = widget.NewTextGridFromString("预览和处理结果将在这里显示")
	view.output.Scroll = fyne.ScrollBoth

	view.browse = widget.NewButtonWithIcon("选择目录", theme.FolderOpenIcon(), func() {
		picker := dialog.NewFolderOpen(func(uri fyne.ListableURI, err error) {
			if err != nil {
				dialog.ShowError(err, window)
				return
			}
			if uri != nil {
				view.root.SetText(filepath.Clean(uri.Path()))
			}
		}, window)
		picker.Show()
	})
	view.previewButton = widget.NewButtonWithIcon("扫描预览", theme.SearchIcon(), func() {
		view.startTask(false)
	})
	view.executeButton = widget.NewButtonWithIcon("执行删除", theme.DeleteIcon(), func() {
		view.requestExecution()
	})
	view.executeButton.Importance = widget.DangerImportance
	view.executeButton.Disable()

	view.controls = []fyne.Disableable{
		view.root, view.mode, view.extensions, view.exclusions, view.contentExclusions,
		view.contentMaxMiB, view.workers, view.previewCount, view.keepPreview,
		view.emptyDirPreview, view.logPath, view.noExtension, view.invert,
		view.emptyDirs, view.ignoreScanErrors, view.browse,
	}
	view.bindChanges()
	return view
}

func (view *guiView) content() fyne.CanvasObject {
	title := widget.NewLabelWithStyle("文件类型清理器", fyne.TextAlignLeading, fyne.TextStyle{Bold: true})
	versionLabel := widget.NewLabel("v" + version + "  GUI")
	header := container.NewBorder(nil, nil, title, versionLabel)
	rootBar := container.NewBorder(nil, nil, widget.NewLabel("根目录"), view.browse, view.root)
	top := container.NewVBox(header, widget.NewSeparator(), rootBar)

	filterForm := widget.NewForm(
		widget.NewFormItem("扩展名", view.extensions),
		widget.NewFormItem("排除路径", view.exclusions),
		widget.NewFormItem("排除内容", view.contentExclusions),
	)
	filterChecks := container.NewGridWithColumns(2, view.noExtension, view.invert, view.emptyDirs)
	filterPanel := container.NewVScroll(container.NewVBox(
		widget.NewLabelWithStyle("处理模式", fyne.TextAlignLeading, fyne.TextStyle{Bold: true}),
		view.mode,
		widget.NewSeparator(),
		filterForm,
		widget.NewSeparator(),
		filterChecks,
	))

	settingsForm := widget.NewForm(
		widget.NewFormItem("内容上限 MiB", view.contentMaxMiB),
		widget.NewFormItem("并发数", view.workers),
		widget.NewFormItem("处理预览数", view.previewCount),
		widget.NewFormItem("保留预览数", view.keepPreview),
		widget.NewFormItem("空目录预览数", view.emptyDirPreview),
		widget.NewFormItem("日志文件", view.logPath),
	)
	settingsPanel := container.NewVScroll(container.NewVBox(settingsForm, view.ignoreScanErrors))
	leftTabs := container.NewAppTabs(
		container.NewTabItemWithIcon("规则", theme.SearchIcon(), filterPanel),
		container.NewTabItemWithIcon("设置", theme.SettingsIcon(), settingsPanel),
	)
	leftTabs.SetTabLocation(container.TabLocationTop)
	actions := container.NewGridWithColumns(2, view.previewButton, view.executeButton)
	left := container.NewBorder(nil, actions, nil, nil, leftTabs)

	resultHeader := container.NewVBox(
		container.NewBorder(nil, nil, widget.NewLabelWithStyle("处理结果", fyne.TextAlignLeading, fyne.TextStyle{Bold: true}), nil, view.status),
		view.progressInfinite,
		view.progress,
	)
	right := container.NewBorder(resultHeader, nil, nil, nil, view.output)
	split := container.NewHSplit(container.NewPadded(left), container.NewPadded(right))
	split.Offset = 0.42

	return container.NewBorder(container.NewPadded(top), nil, nil, nil, split)
}

func (view *guiView) bindChanges() {
	changed := func(string) { view.markChanged() }
	view.root.OnChanged = changed
	view.extensions.OnChanged = changed
	view.exclusions.OnChanged = changed
	view.contentExclusions.OnChanged = changed
	view.contentMaxMiB.OnChanged = changed
	view.workers.OnChanged = changed
	view.previewCount.OnChanged = changed
	view.keepPreview.OnChanged = changed
	view.emptyDirPreview.OnChanged = changed
	view.logPath.OnChanged = changed
	view.noExtension.OnChanged = func(bool) { view.markChanged() }
	view.invert.OnChanged = func(bool) { view.markChanged() }
	view.emptyDirs.OnChanged = func(bool) { view.markChanged() }
	view.ignoreScanErrors.OnChanged = func(bool) { view.markChanged() }
	view.mode.OnChanged = func(mode string) {
		if mode == guiModeFlatten {
			view.executeButton.SetText("执行展平")
			view.executeButton.SetIcon(theme.SearchReplaceIcon())
			view.executeButton.Importance = widget.HighImportance
		} else {
			view.executeButton.SetText("执行删除")
			view.executeButton.SetIcon(theme.DeleteIcon())
			view.executeButton.Importance = widget.DangerImportance
		}
		view.executeButton.Refresh()
		view.markChanged()
	}
}

func (view *guiView) markChanged() {
	if view.running {
		return
	}
	view.lastPreview = ""
	view.executeButton.Disable()
	view.status.SetText("设置已更改")
}

func (view *guiView) options() guiOptions {
	return guiOptions{
		root:              view.root.Text,
		mode:              view.mode.Selected,
		extensions:        view.extensions.Text,
		exclusions:        view.exclusions.Text,
		contentExclusions: view.contentExclusions.Text,
		contentMaxMiB:     view.contentMaxMiB.Text,
		workers:           view.workers.Text,
		preview:           view.previewCount.Text,
		keepPreview:       view.keepPreview.Text,
		emptyDirPreview:   view.emptyDirPreview.Text,
		logPath:           view.logPath.Text,
		noExtension:       view.noExtension.Checked,
		invert:            view.invert.Checked,
		emptyDirs:         view.emptyDirs.Checked,
		ignoreScanErrors:  view.ignoreScanErrors.Checked,
	}
}

func (view *guiView) requestExecution() {
	options := view.options()
	if options.fingerprint() != view.lastPreview || view.lastPreview == "" {
		dialog.ShowInformation("需要重新预览", "当前设置尚未成功预览，或预览后设置已经变化。", view.window)
		return
	}
	message := "将按上次预览永久删除所选文件。删除不会进入回收站。"
	if options.mode == guiModeFlatten {
		message = "将按上次预览把文件移动到根目录；重复名称会自动编号。"
	}
	dialog.NewConfirm("确认执行", message, func(confirmed bool) {
		if confirmed {
			view.startTask(true)
		}
	}, view.window).Show()
}

func (view *guiView) startTask(execute bool) {
	if view.running {
		return
	}
	options := view.options()
	if strings.TrimSpace(options.root) == "" {
		dialog.ShowError(errors.New("请选择根目录"), view.window)
		return
	}
	previewFingerprint := options.fingerprint()
	args := options.arguments(execute)
	view.setRunning(true)
	view.output.SetText("")
	view.status.SetText("正在扫描")
	view.progress.Hide()
	view.progressInfinite.Show()

	go func() {
		var stdout bytes.Buffer
		stderr := &guiRunOutput{progress: view.updateProgress}
		code := run(args, strings.NewReader(""), &stdout, stderr)
		result := combineGUIOutput(stdout.String(), stderr.String())
		fyne.Do(func() {
			view.finishTask(execute, previewFingerprint, code, result)
		})
	}()
}

func (view *guiView) updateProgress(state progressState) {
	fyne.Do(func() {
		if state.phase == "scan" {
			view.progress.Hide()
			view.progressInfinite.Show()
			view.status.SetText(fmt.Sprintf("扫描中  |  已扫描 %s  |  已选择 %s", formatInteger(state.processed), formatInteger(state.selected)))
			return
		}
		view.progressInfinite.Hide()
		view.progress.Show()
		value := float64(0)
		if state.total > 0 {
			value = float64(state.processed) / float64(state.total)
		}
		view.progress.SetValue(value)
		phase := map[string]string{"delete": "删除", "move": "移动", "directories": "空目录"}[state.phase]
		view.status.SetText(fmt.Sprintf("%s  %s/%s  |  成功 %s  |  失败 %s", phase, formatInteger(state.processed), formatInteger(state.total), formatInteger(state.succeeded), formatInteger(state.failed)))
	})
}

func (view *guiView) finishTask(execute bool, previewFingerprint string, code int, result string) {
	view.output.SetText(result)
	view.output.ScrollToTop()
	view.progress.Hide()
	view.progressInfinite.Hide()
	view.setRunning(false)

	if code == 0 {
		if execute {
			view.lastPreview = ""
			view.executeButton.Disable()
			view.status.SetText("处理完成")
			dialog.ShowInformation("处理完成", "操作已完成，详细结果显示在结果区域。", view.window)
		} else {
			view.lastPreview = previewFingerprint
			view.executeButton.Enable()
			view.status.SetText("预览完成，可以执行")
		}
		return
	}
	view.lastPreview = ""
	view.executeButton.Disable()
	view.status.SetText(fmt.Sprintf("处理未完成  |  返回码 %d", code))
}

func (view *guiView) setRunning(running bool) {
	view.running = running
	for _, control := range view.controls {
		if running {
			control.Disable()
		} else {
			control.Enable()
		}
	}
	if running {
		view.previewButton.Disable()
		view.executeButton.Disable()
	} else {
		view.previewButton.Enable()
	}
}

func combineGUIOutput(stdout, stderr string) string {
	stdout = strings.TrimSpace(stdout)
	stderr = strings.TrimSpace(stderr)
	switch {
	case stdout == "":
		return stderr
	case stderr == "":
		return stdout
	default:
		return stdout + "\n\n诊断与进度\n" + stderr
	}
}
