package main

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestNormalizeExtensions(t *testing.T) {
	got, err := normalizeExtensions("c, .H, *.tar.gz, none, .c")
	if err != nil {
		t.Fatal(err)
	}
	want := []string{".tar.gz", ".c", ".h", ""}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("got %#v, want %#v", got, want)
	}
}

func TestNormalizeExclusions(t *testing.T) {
	got, err := normalizeExclusions(" Vendor, TEMP, vendor ")
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"temp", "vendor"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("got %#v, want %#v", got, want)
	}
}

func TestNormalizeContentExclusions(t *testing.T) {
	got, err := normalizeContentExclusions(" Generated By, DO NOT DELETE,generated by ")
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"do not delete", "generated by"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("got %#v, want %#v", got, want)
	}
}

func TestMatchPatternUsesLongestSuffix(t *testing.T) {
	patterns, err := normalizeExtensions(".gz,.tar.gz")
	if err != nil {
		t.Fatal(err)
	}
	got, ok := matchPattern("ARCHIVE.TAR.GZ", patterns)
	if !ok || got != ".tar.gz" {
		t.Fatalf("got %q, %v", got, ok)
	}
}

func TestNoExtensionOption(t *testing.T) {
	root := t.TempDir()
	for name, content := range map[string]string{
		"LICENSE":    "no extension",
		".gitignore": "dot file",
		"keep.txt":   "extension",
	} {
		if err := os.WriteFile(filepath.Join(root, name), []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{"--root", root, "--no-ext", "--preview", "10"}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	output := stdout.String()
	if !strings.Contains(output, "LICENSE") || strings.Contains(output, ".gitignore") || strings.Contains(output, "keep.txt") {
		t.Fatalf("unexpected no-extension preview: %q", output)
	}
}

func TestNoExtensionCanCombineWithExtensions(t *testing.T) {
	root := t.TempDir()
	for _, name := range []string{"LICENSE", "keep.txt", "keep.go"} {
		if err := os.WriteFile(filepath.Join(root, name), nil, 0o600); err != nil {
			t.Fatal(err)
		}
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{"--root", root, "--ext", ".txt", "--no-ext", "--preview", "10"}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	output := stdout.String()
	if !strings.Contains(output, "LICENSE") || !strings.Contains(output, "keep.txt") || strings.Contains(output, "keep.go") {
		t.Fatalf("unexpected combined preview: %q", output)
	}
}

func TestExcludeKeywordsSkipFilesAndDirectoryTrees(t *testing.T) {
	root := filepath.Join(t.TempDir(), "vendor-root")
	paths := map[string]string{
		filepath.Join("src", "keep.h"):              "keep",
		filepath.Join("src", "KEEP_ME-generated.h"): "excluded file",
		filepath.Join("vendor", "deep", "drop.h"):   "excluded tree",
	}
	for name, content := range paths {
		fullPath := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{
		"--root", root,
		"--ext", ".h",
		"--exclude", "VENDOR,keep_me",
		"--preview", "10",
	}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	output := stdout.String()
	if !strings.Contains(output, filepath.Join("src", "keep.h")) || strings.Contains(output, "drop.h") {
		t.Fatalf("unexpected exclusion preview: %q", output)
	}
	if !strings.Contains(output, "[路径关键词] "+filepath.Join(root, "src", "KEEP_ME-generated.h")) ||
		!strings.Contains(output, "[路径关键词（目录树）] "+filepath.Join(root, "vendor")) {
		t.Fatalf("missing retained path preview: %q", output)
	}
	if !strings.Contains(output, "排除命中: 2") || !strings.Contains(output, "目录 1") {
		t.Fatalf("missing exclusion summary: %q", output)
	}
}

func TestContentKeywordsExcludeMatchingFiles(t *testing.T) {
	root := t.TempDir()
	protected := filepath.Join(root, "protected.txt")
	removed := filepath.Join(root, "removed.txt")
	if err := os.WriteFile(protected, []byte("Generated file - DO NOT DELETE"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(removed, []byte("ordinary content"), 0o600); err != nil {
		t.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	args := []string{
		"--root", root,
		"--ext", ".txt",
		"--exclude-content", "do not delete",
		"--preview", "10",
	}
	code := run(args, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("preview code=%d, stderr=%q", code, stderr.String())
	}
	output := stdout.String()
	if !strings.Contains(output, "removed.txt") ||
		!strings.Contains(output, "[内容关键词] "+protected) {
		t.Fatalf("unexpected content exclusion preview: %q", output)
	}
	if !strings.Contains(output, "内容关键词排除: 1") {
		t.Fatalf("missing content exclusion summary: %q", output)
	}

	stdout.Reset()
	stderr.Reset()
	args = append(args, "--delete", "--yes")
	code = run(args, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("delete code=%d, stderr=%q", code, stderr.String())
	}
	if _, err := os.Lstat(protected); err != nil {
		t.Fatalf("content-protected file was affected: %v", err)
	}
	if _, err := os.Lstat(removed); !os.IsNotExist(err) {
		t.Fatalf("unprotected file still exists or unexpected error: %v", err)
	}
}

func TestContentSizeLimitPreservesLargeFiles(t *testing.T) {
	root := t.TempDir()
	large := filepath.Join(root, "large.txt")
	if err := os.WriteFile(large, bytes.Repeat([]byte("x"), 1024*1024+1), 0o600); err != nil {
		t.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{
		"--root", root,
		"--ext", ".txt",
		"--exclude-content", "protected",
		"--content-max-mib", "1",
		"--preview", "0",
	}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "超过内容上限并保留: 1") {
		t.Fatalf("missing size-limit summary: %q", stdout.String())
	}
	if _, err := os.Lstat(large); err != nil {
		t.Fatalf("large file was affected: %v", err)
	}
}

func TestContentKeywordCanCrossReadBufferBoundary(t *testing.T) {
	root := t.TempDir()
	target := filepath.Join(root, "boundary.txt")
	content := append(bytes.Repeat([]byte("x"), 64*1024-4), []byte("PROTECTED content")...)
	if err := os.WriteFile(target, content, 0o600); err != nil {
		t.Fatal(err)
	}
	filter := newContentFilter([]string{"protected"}, 0)
	matched, tooLarge, _, err := filter.match(target, int64(len(content)))
	if err != nil || !matched || tooLarge {
		t.Fatalf("matched=%v, tooLarge=%v, err=%v", matched, tooLarge, err)
	}
}

func TestContentIsRecheckedBeforeDelete(t *testing.T) {
	root := t.TempDir()
	target := filepath.Join(root, "changing.txt")
	if err := os.WriteFile(target, []byte("ordinary"), 0o600); err != nil {
		t.Fatal(err)
	}
	patterns, err := normalizeExtensions(".txt")
	if err != nil {
		t.Fatal(err)
	}
	filter := newContentFilter([]string{"protect me"}, 1)
	result := scan(root, patterns, nil, false, filter, 0, false, nil)
	if len(result.files) != 1 {
		t.Fatalf("files=%d, want 1", len(result.files))
	}
	if err := os.WriteFile(target, []byte("PROTECT ME"), 0o600); err != nil {
		t.Fatal(err)
	}

	summary, deleteErrors := deleteCandidates(result.files, patterns, false, filter, 1, nil, nil)
	if len(deleteErrors) != 0 || summary.deleted != 0 || summary.skipped != 1 {
		t.Fatalf("summary=%#v, errors=%v", summary, deleteErrors)
	}
	if _, err := os.Lstat(target); err != nil {
		t.Fatalf("file protected during recheck was affected: %v", err)
	}
}

func TestInvertModeKeepsOnlySelectedExtensions(t *testing.T) {
	root := t.TempDir()
	for _, name := range []string{"keep.c", "KEEP.H", "delete.txt", "LICENSE", ".gitignore"} {
		if err := os.WriteFile(filepath.Join(root, name), []byte(name), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	excludedDir := filepath.Join(root, "cache")
	if err := os.MkdirAll(excludedDir, 0o700); err != nil {
		t.Fatal(err)
	}
	excludedFile := filepath.Join(excludedDir, "preserved.tmp")
	if err := os.WriteFile(excludedFile, []byte("excluded"), 0o600); err != nil {
		t.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	args := []string{
		"--root", root,
		"--ext", ".c,.h",
		"--invert",
		"--exclude", "cache",
		"--preview", "10",
	}
	code := run(args, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("preview code=%d, stderr=%q", code, stderr.String())
	}
	output := stdout.String()
	for _, wanted := range []string{"delete.txt", "LICENSE", ".gitignore", "保留命中: 2", "待处理文件: 3"} {
		if !strings.Contains(output, wanted) {
			t.Fatalf("preview missing %q: %q", wanted, output)
		}
	}
	for _, preserved := range []string{"keep.c", "KEEP.H"} {
		if !strings.Contains(output, "[指定保留类型] "+filepath.Join(root, preserved)) {
			t.Fatalf("retained preview missing %q: %q", preserved, output)
		}
	}
	if !strings.Contains(output, "[路径关键词（目录树）] "+excludedDir) || strings.Contains(output, "preserved.tmp") {
		t.Fatalf("unexpected excluded-tree preview: %q", output)
	}

	stdout.Reset()
	stderr.Reset()
	args = append(args, "--delete", "--yes")
	code = run(args, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("delete code=%d, stderr=%q", code, stderr.String())
	}
	for _, preserved := range []string{"keep.c", "KEEP.H", filepath.Join("cache", "preserved.tmp")} {
		if _, err := os.Lstat(filepath.Join(root, preserved)); err != nil {
			t.Fatalf("preserved file %q was affected: %v", preserved, err)
		}
	}
	for _, deleted := range []string{"delete.txt", "LICENSE", ".gitignore"} {
		if _, err := os.Lstat(filepath.Join(root, deleted)); !os.IsNotExist(err) {
			t.Fatalf("candidate %q still exists or unexpected error: %v", deleted, err)
		}
	}
}

func TestInvertModeCanKeepNoExtension(t *testing.T) {
	root := t.TempDir()
	for _, name := range []string{"LICENSE", "keep.c", "delete.txt"} {
		if err := os.WriteFile(filepath.Join(root, name), nil, 0o600); err != nil {
			t.Fatal(err)
		}
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{
		"--root", root,
		"--ext", ".c",
		"--no-ext",
		"--invert",
		"--preview", "10",
	}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	output := stdout.String()
	if !strings.Contains(output, "delete.txt") ||
		!strings.Contains(output, "[指定保留类型] "+filepath.Join(root, "LICENSE")) ||
		!strings.Contains(output, "[指定保留类型] "+filepath.Join(root, "keep.c")) {
		t.Fatalf("unexpected inverse no-extension preview: %q", output)
	}
}

func TestKeepPreviewLimit(t *testing.T) {
	root := t.TempDir()
	for _, name := range []string{"keep.c", "keep.h", "delete.txt"} {
		if err := os.WriteFile(filepath.Join(root, name), nil, 0o600); err != nil {
			t.Fatal(err)
		}
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{
		"--root", root,
		"--ext", ".c,.h",
		"--invert",
		"--preview", "0",
		"--keep-preview", "1",
	}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	output := stdout.String()
	if !strings.Contains(output, "保留预览（前 1 个）") || !strings.Contains(output, "另有 1 个显式保留项") {
		t.Fatalf("unexpected keep-preview limit output: %q", output)
	}
}

func TestEmptyDirectoriesCanBeSelectedAlone(t *testing.T) {
	root := t.TempDir()
	emptyParent := filepath.Join(root, "empty-parent")
	emptyChild := filepath.Join(emptyParent, "empty-child")
	nonEmpty := filepath.Join(root, "non-empty")
	if err := os.MkdirAll(emptyChild, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(nonEmpty, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(nonEmpty, "keep.txt"), []byte("keep"), 0o600); err != nil {
		t.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	args := []string{
		"--root", root,
		"--empty-dirs",
		"--empty-dir-preview", "10",
	}
	code := run(args, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("preview code=%d, stderr=%q", code, stderr.String())
	}
	output := stdout.String()
	if !strings.Contains(output, "空文件夹候选: 2") ||
		!strings.Contains(output, "[当前为空] "+emptyChild) ||
		!strings.Contains(output, "[处理后为空] "+emptyParent) ||
		strings.Contains(output, "[当前为空] "+nonEmpty) {
		t.Fatalf("unexpected empty-directory preview: %q", output)
	}

	stdout.Reset()
	stderr.Reset()
	args = append(args, "--delete", "--yes")
	code = run(args, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("delete code=%d, stderr=%q", code, stderr.String())
	}
	if _, err := os.Lstat(emptyParent); !os.IsNotExist(err) {
		t.Fatalf("empty directory tree still exists or unexpected error: %v", err)
	}
	if _, err := os.Lstat(nonEmpty); err != nil {
		t.Fatalf("non-empty directory was affected: %v", err)
	}
}

func TestDirectoryBecomesEmptyAfterSelectedFilesAreDeleted(t *testing.T) {
	root := t.TempDir()
	targetDir := filepath.Join(root, "remove-tree", "nested")
	if err := os.MkdirAll(targetDir, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(targetDir, "remove.tmp"), []byte("remove"), 0o600); err != nil {
		t.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{
		"--root", root,
		"--ext", ".tmp",
		"--empty-dirs",
		"--delete",
		"--yes",
	}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	if _, err := os.Lstat(filepath.Join(root, "remove-tree")); !os.IsNotExist(err) {
		t.Fatalf("directory that became empty still exists or unexpected error: %v", err)
	}
	if !strings.Contains(stdout.String(), "空文件夹已删除: 2") {
		t.Fatalf("missing directory deletion summary: %q", stdout.String())
	}
}

func TestExcludedEmptyDirectoryIsPreserved(t *testing.T) {
	root := t.TempDir()
	excluded := filepath.Join(root, "cache")
	if err := os.MkdirAll(excluded, 0o700); err != nil {
		t.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{
		"--root", root,
		"--empty-dirs",
		"--exclude", "cache",
		"--delete",
		"--yes",
	}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	if _, err := os.Lstat(excluded); err != nil {
		t.Fatalf("excluded empty directory was affected: %v", err)
	}
	if !strings.Contains(stdout.String(), "[路径关键词（目录树）] "+excluded) {
		t.Fatalf("missing excluded directory keep preview: %q", stdout.String())
	}
}

func TestEmptyDirectoryIsRecheckedBeforeDelete(t *testing.T) {
	root := t.TempDir()
	directory := filepath.Join(root, "changing")
	if err := os.MkdirAll(directory, 0o700); err != nil {
		t.Fatal(err)
	}
	directories := []emptyDirectory{{path: directory}}
	if err := os.WriteFile(filepath.Join(directory, "new.txt"), []byte("new"), 0o600); err != nil {
		t.Fatal(err)
	}

	summary, deleteErrors := deleteEmptyDirectories(directories, nil, nil)
	if len(deleteErrors) != 0 || summary.deleted != 0 || summary.skipped != 1 {
		t.Fatalf("summary=%#v, errors=%v", summary, deleteErrors)
	}
	if _, err := os.Lstat(directory); err != nil {
		t.Fatalf("directory that became non-empty was affected: %v", err)
	}
}

func TestDryRunAndDelete(t *testing.T) {
	root := t.TempDir()
	target := filepath.Join(root, "delete.C")
	keep := filepath.Join(root, "keep.txt")
	if err := os.WriteFile(target, []byte("target"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(keep, []byte("keep"), 0o600); err != nil {
		t.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{"--root", root, "--ext", ".c", "--preview", "0"}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("dry run code %d, stderr: %s", code, stderr.String())
	}
	if _, err := os.Stat(target); err != nil {
		t.Fatalf("dry run removed target: %v", err)
	}

	stdout.Reset()
	stderr.Reset()
	code = run([]string{"--root", root, "--ext", ".c", "--preview", "0", "--delete", "--yes"}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("delete code %d, stderr: %s", code, stderr.String())
	}
	if _, err := os.Stat(target); !os.IsNotExist(err) {
		t.Fatalf("target still exists or unexpected error: %v", err)
	}
	if _, err := os.Stat(keep); err != nil {
		t.Fatalf("non-target file was affected: %v", err)
	}
}

func TestZeroByteFileIsCountedAndDeleted(t *testing.T) {
	root := t.TempDir()
	target := filepath.Join(root, "msm_io_ids.h")
	if err := os.WriteFile(target, nil, 0o600); err != nil {
		t.Fatal(err)
	}
	patterns, err := normalizeExtensions(".h")
	if err != nil {
		t.Fatal(err)
	}

	result := scan(root, patterns, nil, false, contentFilter{}, 0, false, nil)
	if len(result.files) != 1 || result.zeroSize != 1 {
		t.Fatalf("files=%d, zeroSize=%d, want 1 and 1", len(result.files), result.zeroSize)
	}
	if result.files[0].size != 0 || result.files[0].isLinkLike {
		t.Fatalf("unexpected candidate: %#v", result.files[0])
	}

	summary, deleteErrors := deleteCandidates(result.files, patterns, false, contentFilter{}, 1, nil, nil)
	if len(deleteErrors) != 0 || summary.deleted != 1 {
		t.Fatalf("summary=%#v, errors=%v", summary, deleteErrors)
	}
	if _, err := os.Lstat(target); !os.IsNotExist(err) {
		t.Fatalf("zero-byte target still exists or unexpected error: %v", err)
	}
}

func TestSymlinkIsCountedAndOnlyLinkIsDeleted(t *testing.T) {
	root := t.TempDir()
	target := filepath.Join(root, "target.txt")
	link := filepath.Join(root, "internal.h")
	if err := os.WriteFile(target, []byte("keep target"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(target, link); err != nil {
		t.Skipf("cannot create symlink in this environment: %v", err)
	}
	patterns, err := normalizeExtensions(".h")
	if err != nil {
		t.Fatal(err)
	}

	filter := newContentFilter([]string{"keep target"}, 1)
	result := scan(root, patterns, nil, false, filter, 0, false, nil)
	if len(result.files) != 1 || result.linkLikes != 1 || !result.files[0].isLinkLike {
		t.Fatalf("files=%#v, linkLikes=%d", result.files, result.linkLikes)
	}

	summary, deleteErrors := deleteCandidates(result.files, patterns, false, filter, 1, nil, nil)
	if len(deleteErrors) != 0 || summary.deleted != 1 || summary.linkLikes != 1 {
		t.Fatalf("summary=%#v, errors=%v", summary, deleteErrors)
	}
	if _, err := os.Lstat(link); !os.IsNotExist(err) {
		t.Fatalf("link still exists or unexpected error: %v", err)
	}
	if data, err := os.ReadFile(target); err != nil || string(data) != "keep target" {
		t.Fatalf("symlink target was affected: data=%q, err=%v", data, err)
	}
}

func TestDeleteProgressUsesFileCount(t *testing.T) {
	var output bytes.Buffer
	display := newProgressDisplay(&output)
	display.delete(1, 1, 1, 0, true)
	if got := output.String(); !strings.Contains(got, "100%") || !strings.Contains(got, "1/1") {
		t.Fatalf("unexpected progress output: %q", got)
	}
}

func TestFlattenPreviewAndApply(t *testing.T) {
	root := t.TempDir()
	source := filepath.Join(root, "a", "b", "file.txt")
	if err := os.MkdirAll(filepath.Dir(source), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(source, []byte("nested"), 0o600); err != nil {
		t.Fatal(err)
	}
	rootFile := filepath.Join(root, "root.txt")
	if err := os.WriteFile(rootFile, []byte("root"), 0o600); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(root, "a__b__file.txt")

	var stdout, stderr bytes.Buffer
	args := []string{"--root", root, "--flatten", "--preview", "10", "--keep-preview", "10"}
	code := run(args, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("preview code=%d, stderr=%q", code, stderr.String())
	}
	output := stdout.String()
	if !strings.Contains(output, source) || !strings.Contains(output, "-> "+target) || !strings.Contains(output, "[已在根目录] "+rootFile) {
		t.Fatalf("unexpected preview: %q", output)
	}
	if _, err := os.Stat(source); err != nil {
		t.Fatalf("preview affected source: %v", err)
	}
	if _, err := os.Stat(target); !os.IsNotExist(err) {
		t.Fatalf("preview created target or returned unexpected error: %v", err)
	}

	stdout.Reset()
	stderr.Reset()
	code = run(append(args, "--apply", "--yes"), strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("apply code=%d, stderr=%q", code, stderr.String())
	}
	if _, err := os.Stat(source); !os.IsNotExist(err) {
		t.Fatalf("source still exists or unexpected error: %v", err)
	}
	if data, err := os.ReadFile(target); err != nil || string(data) != "nested" {
		t.Fatalf("unexpected target: data=%q, err=%v", data, err)
	}
	if data, err := os.ReadFile(rootFile); err != nil || string(data) != "root" {
		t.Fatalf("root file was affected: data=%q, err=%v", data, err)
	}
}

func TestFlattenNumbersPastExistingTargetsWithoutOverwriting(t *testing.T) {
	root := t.TempDir()
	source := filepath.Join(root, "a", "file.txt")
	if err := os.MkdirAll(filepath.Dir(source), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(source, []byte("source"), 0o600); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(root, "A__FILE.TXT")
	if err := os.WriteFile(target, []byte("existing"), 0o600); err != nil {
		t.Fatal(err)
	}
	secondTarget := filepath.Join(root, "a__file (2).txt")
	if err := os.WriteFile(secondTarget, []byte("existing 2"), 0o600); err != nil {
		t.Fatal(err)
	}
	numberedTarget := filepath.Join(root, "a__file (3).txt")

	var stdout, stderr bytes.Buffer
	code := run([]string{"--root", root, "--flatten", "--apply", "--yes", "--keep-preview", "10"}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "重复名称自动编号: 1") || !strings.Contains(stdout.String(), "-> "+numberedTarget) {
		t.Fatalf("missing numbered target: %q", stdout.String())
	}
	if _, err := os.Stat(source); !os.IsNotExist(err) {
		t.Fatalf("source still exists or unexpected error: %v", err)
	}
	if data, err := os.ReadFile(target); err != nil || string(data) != "existing" {
		t.Fatalf("existing target was overwritten: data=%q, err=%v", data, err)
	}
	if data, err := os.ReadFile(secondTarget); err != nil || string(data) != "existing 2" {
		t.Fatalf("second existing target was overwritten: data=%q, err=%v", data, err)
	}
	if data, err := os.ReadFile(numberedTarget); err != nil || string(data) != "source" {
		t.Fatalf("numbered target was not created: data=%q, err=%v", data, err)
	}
}

func TestFlattenNumbersGeneratedNameCollisions(t *testing.T) {
	root := t.TempDir()
	sources := []string{
		filepath.Join(root, "a", "b__file.txt"),
		filepath.Join(root, "a__b", "file.txt"),
	}
	for _, source := range sources {
		if err := os.MkdirAll(filepath.Dir(source), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(source, []byte(source), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	result := scanFlatten(root, nil, false, nil, false, contentFilter{}, 10, false, nil)
	if len(result.files) != 2 || result.numbered != 1 {
		t.Fatalf("files=%d, numbered=%d", len(result.files), result.numbered)
	}
	wantTargets := []string{
		filepath.Join(root, "a__b__file.txt"),
		filepath.Join(root, "a__b__file (2).txt"),
	}
	for index, want := range wantTargets {
		if result.files[index].target != want {
			t.Fatalf("target[%d]=%q, want %q", index, result.files[index].target, want)
		}
	}
	summary, moveErrors := moveCandidates(result.files, root, nil, false, false, contentFilter{}, 1, nil, nil)
	if len(moveErrors) != 0 || summary.moved != 2 {
		t.Fatalf("summary=%#v, errors=%v", summary, moveErrors)
	}
	for index, target := range wantTargets {
		if data, err := os.ReadFile(target); err != nil || string(data) != sources[index] {
			t.Fatalf("target[%d]: data=%q, err=%v", index, data, err)
		}
	}
}

func TestFlattenKeepsLinksInPlace(t *testing.T) {
	root := t.TempDir()
	target := filepath.Join(root, "target.txt")
	if err := os.WriteFile(target, []byte("target"), 0o600); err != nil {
		t.Fatal(err)
	}
	directory := filepath.Join(root, "nested")
	if err := os.MkdirAll(directory, 0o700); err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(directory, "link.txt")
	if err := os.Symlink(target, link); err != nil {
		t.Skipf("cannot create symlink in this environment: %v", err)
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{"--root", root, "--flatten", "--apply", "--yes", "--keep-preview", "10"}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	if _, err := os.Lstat(link); err != nil {
		t.Fatalf("link was affected: %v", err)
	}
	if data, err := os.ReadFile(target); err != nil || string(data) != "target" {
		t.Fatalf("link target was affected: data=%q, err=%v", data, err)
	}
	if !strings.Contains(stdout.String(), "[链接不参与展平] "+link) {
		t.Fatalf("missing retained link preview: %q", stdout.String())
	}
}

func TestFlattenHonorsTypePathAndContentFilters(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{
		filepath.Join("src", "move.txt"):      "move",
		filepath.Join("src", "type.go"):       "type",
		filepath.Join("src", "protected.txt"): "KEEP THIS",
		filepath.Join("vendor", "skip.txt"):   "excluded",
	}
	for relative, content := range files {
		path := filepath.Join(root, relative)
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{
		"--root", root,
		"--flatten",
		"--ext", ".txt",
		"--exclude", "vendor",
		"--exclude-content", "keep this",
		"--apply",
		"--yes",
	}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	if data, err := os.ReadFile(filepath.Join(root, "src__move.txt")); err != nil || string(data) != "move" {
		t.Fatalf("selected file not moved: data=%q, err=%v", data, err)
	}
	for _, relative := range []string{filepath.Join("src", "type.go"), filepath.Join("src", "protected.txt"), filepath.Join("vendor", "skip.txt")} {
		if _, err := os.Stat(filepath.Join(root, relative)); err != nil {
			t.Fatalf("retained file %q was affected: %v", relative, err)
		}
	}
}

func TestFlattenInvertMovesUnselectedTypes(t *testing.T) {
	root := t.TempDir()
	directory := filepath.Join(root, "nested")
	if err := os.MkdirAll(directory, 0o700); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"keep.txt", "move.go"} {
		if err := os.WriteFile(filepath.Join(directory, name), []byte(name), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{"--root", root, "--flatten", "--ext", ".txt", "--invert", "--apply", "--yes"}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	if _, err := os.Stat(filepath.Join(directory, "keep.txt")); err != nil {
		t.Fatalf("selected retained type was affected: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "nested__move.go")); err != nil {
		t.Fatalf("unselected type was not moved: %v", err)
	}
}

func TestFlattenCanRemoveDirectoriesAfterMoving(t *testing.T) {
	root := t.TempDir()
	source := filepath.Join(root, "one", "two", "file.txt")
	if err := os.MkdirAll(filepath.Dir(source), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(source, []byte("move"), 0o600); err != nil {
		t.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	code := run([]string{"--root", root, "--flatten", "--empty-dirs", "--apply", "--yes"}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
	if _, err := os.Stat(filepath.Join(root, "one")); !os.IsNotExist(err) {
		t.Fatalf("empty source tree remains or unexpected error: %v", err)
	}
	if !strings.Contains(stdout.String(), "空文件夹已删除: 2") {
		t.Fatalf("unexpected summary: %q", stdout.String())
	}
}

func TestFlattenSkippedMoveKeepsSourceDirectory(t *testing.T) {
	root := t.TempDir()
	source := filepath.Join(root, "nested", "file.txt")
	if err := os.MkdirAll(filepath.Dir(source), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(source, []byte("source"), 0o600); err != nil {
		t.Fatal(err)
	}
	result := scanFlatten(root, nil, false, nil, false, contentFilter{}, 0, true, nil)
	if len(result.files) != 1 || len(result.emptyDirs) != 1 {
		t.Fatalf("unexpected plan: files=%d, emptyDirs=%d", len(result.files), len(result.emptyDirs))
	}
	if err := os.WriteFile(result.files[0].target, []byte("new target"), 0o600); err != nil {
		t.Fatal(err)
	}
	summary, moveErrors := moveCandidates(result.files, root, nil, false, false, contentFilter{}, 1, nil, nil)
	if len(moveErrors) != 0 || summary.skipped != 1 || summary.moved != 0 {
		t.Fatalf("summary=%#v, errors=%v", summary, moveErrors)
	}
	directorySummary, directoryErrors := deleteEmptyDirectories(result.emptyDirs, nil, nil)
	if len(directoryErrors) != 0 || directorySummary.skipped != 1 || directorySummary.deleted != 0 {
		t.Fatalf("directory summary=%#v, errors=%v", directorySummary, directoryErrors)
	}
	if _, err := os.Stat(filepath.Dir(source)); err != nil {
		t.Fatalf("non-empty source directory was affected: %v", err)
	}
}

func TestFlattenRejectsInvalidExecutionFlagCombinations(t *testing.T) {
	root := t.TempDir()
	tests := [][]string{
		{"--root", root, "--flatten", "--delete"},
		{"--root", root, "--ext", ".txt", "--apply"},
	}
	for _, args := range tests {
		var stdout, stderr bytes.Buffer
		if code := run(args, strings.NewReader(""), &stdout, &stderr); code != 2 {
			t.Fatalf("args=%v, code=%d, stderr=%q", args, code, stderr.String())
		}
	}
}

func TestFlattenRetainsGeneratedFilenameOver255UTF16Units(t *testing.T) {
	root := t.TempDir()
	first := strings.Repeat("a", 130)
	second := strings.Repeat("b", 125) + ".txt"
	source := filepath.Join(root, first, second)
	if err := os.MkdirAll(filepath.Dir(source), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(source, nil, 0o600); err != nil {
		t.Fatal(err)
	}

	result := scanFlatten(root, nil, false, nil, false, contentFilter{}, 10, false, nil)
	if len(result.files) != 0 || result.tooLong != 1 {
		t.Fatalf("files=%d, tooLong=%d", len(result.files), result.tooLong)
	}
	if len(result.retained) != 1 || result.retained[0].reason != retainedFlattenTooLong {
		t.Fatalf("unexpected retained result: %#v", result.retained)
	}
}

func TestMoveProgressUsesFileCount(t *testing.T) {
	var output bytes.Buffer
	display := newProgressDisplay(&output)
	display.move(1, 1, 1, 0, true)
	if got := output.String(); !strings.Contains(got, "100%") || !strings.Contains(got, "1/1") || !strings.Contains(got, "成功 1") {
		t.Fatalf("unexpected progress output: %q", got)
	}
}

func TestRejectsVolumeRootDeletion(t *testing.T) {
	volumeRoot := filepath.VolumeName(t.TempDir()) + string(filepath.Separator)
	if filepath.VolumeName(volumeRoot) == "" {
		t.Skip("test requires a volume path")
	}
	var stdout, stderr bytes.Buffer
	code := run([]string{"--root", volumeRoot, "--ext", ".unlikely", "--delete", "--yes"}, strings.NewReader(""), &stdout, &stderr)
	if code != 2 || !strings.Contains(stderr.String(), "安全限制") {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
}

func TestHelpReturnsSuccess(t *testing.T) {
	var stdout, stderr bytes.Buffer
	code := run([]string{"--help"}, strings.NewReader(""), &stdout, &stderr)
	if code != 0 || !strings.Contains(stderr.String(), "用法:") {
		t.Fatalf("code=%d, stderr=%q", code, stderr.String())
	}
}
